name: setup-acts
description: Setup Atian Tools on your Github Actions workflows.
author: ate47
branding:
  icon: "tool"
  color: "green"
categories:
  - "utilities"
  - "tools"
inputs:
  version:
    description: "Version to install (e.g. 3.1.0 or latest)"
    required: false
    default: "latest"
  hashindex:
    description: "Download hash index after installation"
    required: false
    default: false
outputs:
  acts-path:
    description: "Path to the atian tools binaries directory"
runs:
  using: "node20"
  main: "lib/main.js"
